---
KZT:
  :meta_country:
  - Казахстане
  - Казахстана
  - Казахстан
  :meta_currency:
  - казахстанских тенге
UAH:
  :meta_currency:
  - украинских гривнах  
  :meta_country:
  - Украине
  - Украины
  - Украина
UZS:
  :meta_country:
  - Узбекистане
  - Узбекистана
  - Узбекистан
  :meta_currency:
  - узбекских сомах
KGS:
  :meta_country:
  - Кыргызстане
  - Кыргызстана
  - Кыргызстан
  :meta_currency:
  - кыргызских сомах
  - кыргызский сом
RUB:
  :meta_country:
  - России
  - России
  - Россия
  :meta_currency:
  - российских рублях
BYN:
  :meta_country:
  - Беларуси
  - Беларуси
  - Беларусь
  :meta_currency:
  - беларусских рублях
AZN:
  :meta_country:
  - Азербайджане
  - Азербайджана
  - Азербайджан
  :meta_currency:
  - манат
AMD:
  :meta_country:
  - Армении
  - Армении
  - Армения
  :meta_currency:
  - армянских драмах
GEL:
  :meta_country:
  - Грузии
  - Грузии
  - Грузия
  :meta_currency:
  - грузинских лари
MDL:
  :meta_country:
  - Молдове
  - Молдовы
  - Молдова
  :meta_currency:
  - молдовских леях
TJS:
  :meta_country:
  - Таджикистане
  - Таджикистана
  - Таджикистан
  :meta_currency:
  - таджикских сомони
TMT:
  :meta_country:
  - Туркменистане
  - Туркменистана
  - Туркменистан
  :meta_currency:
  - туркменских манатах