---
KZT:
  :meta_country:
  - Казахстане
  - Казахстана
  - Казахстан
  :meta_currency:
  - казахстанских тенге
  - Qazaqstan teñgesi
UAH:
  :meta_currency:
  - украинских гривнах
  - Українська гривня
  :meta_country:
  - Украине
  - Украины
  - Украина
UZS:
  :meta_country:
  - Узбекистане
  - Узбекистана
  - Узбекистан
  :meta_currency:
  - узбекских сумах
  - O'zbekiston so'mi
KGS:
  :meta_country:
  - Кыргызстане
  - Кыргызстана
  - Кыргызстан
  :meta_currency:
  - кыргызских сомах
  - Кыргыз сому
RUB:
  :meta_country:
  - России
  - России
  - Россия
  :meta_currency:
  - российских рублях
  - Российский рубль
BYN:
  :meta_country:
  - Беларуси
  - Беларуси
  - Беларусь
  :meta_currency:
  - беларусских рублях
  - Беларускі рубель
AZN:
  :meta_country:
  - Азербайджане
  - Азербайджана
  - Азербайджан
  :meta_currency:
  - манат
  - Azərbaycan manatı
AMD:
  :meta_country:
  - Армении
  - Армении
  - Армения
  :meta_currency:
  - армянских драмах
  - Հայկական դրամ
GEL:
  :meta_country:
  - Грузии
  - Грузии
  - Грузия
  :meta_currency:
  - грузинских лари
  - ქართული ლარი
MDL:
  :meta_country:
  - Молдове
  - Молдовы
  - Молдова
  :meta_currency:
  - молдовских леях
  - Leu moldovenesc
TJS:
  :meta_country:
  - Таджикистане
  - Таджикистана
  - Таджикистан
  :meta_currency:
  - таджикских сомони
  - Тоҷикистон сомонӣ
TMT:
  :meta_country:
  - Туркменистане
  - Туркменистана
  - Туркменистан
  :meta_currency:
  - туркменских манатах
  - Türkmen Manaty